
[database]
connection = mysql+pymysql://nova-user:nova-password@/nova_cell1?unix_socket=/run/mysqld/mysqld.sock

[conductor]
workers = 2

[DEFAULT]
logging_exception_prefix = ERROR %(name)s [01;35m%(instance)s[00m
logging_default_format_string = %(color)s%(levelname)s %(name)s [[00;36m-%(color)s] [01;35m%(instance)s%(color)s%(message)s[00m
logging_context_format_string = %(color)s%(levelname)s %(name)s [[01;36m%(global_request_id)s %(request_id)s [00;36m%(project_name)s %(user_name)s%(color)s] [01;35m%(instance)s%(color)s%(message)s[00m
logging_debug_format_suffix = [00;33m{{"{{"}}(pid=%(process)d) %(funcName)s %(pathname)s:%(lineno)d{{"}}"}}[00m
transport_url = rabbit://nova:password@{{ template "helpers.labels.fullname" . }}:5672/nova?ssl=1&ssl_ca_file=/run/secrets/airshipit.org/tls/ca/ca.crt
debug = True
